// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

export const ENV_RESOURCE_CONNECTION_STRING = 'RESOURCE_CONNECTION_STRING';
export const ENV_ENDPOINT_URL = 'ENDPOINT_URL';
export const ENV_AZURE_OPENAI_SERVICE_KEY = 'AZURE_OPENAI_SERVICE_KEY';
export const ENV_AZURE_OPENAI_SERVICE_ENDPOINT = 'AZURE_OPENAI_SERVICE_ENDPOINT';
export const ENV_AZURE_OPENAI_SERVICE_DEPLOYMENT_MODEL_NAME = 'AZURE_OPENAI_SERVICE_DEPLOYMENT_MODEL_NAME';
export const ENV_SERVER_CALLBACK_URI = 'SERVER_CALLBACK_URI';
export const ENV_AZURE_OPENAI_PROMPT_INSTRUCTIONS = 'AZURE_OPENAI_PROMPT_INSTRUCTIONS';